### ISSUE TITLE
Doesn't work with ESP32

### ISSUE THREAD

**Issue by yufuping** [simplefoc/Arduino-FOC-balancer#4]
MPU6050 dies at initialize()

Environment:
1. ESP32 Ver2.03

**Comment by askuric** [comment]
Hey @yufuping,

Youre right with the newer version of the Espressif framework the i2cdev library stopped working : https://github.com/jrowberg/i2cdevlib/issues/688

I've updated the i2c dev library in this repo and implemented the propsed fix. The code now works again 😄
